### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by diogo7santiago** [chakrakan/huntr-exporter#101]
Getting this error:

(tutorial-env) C:\Users\RahMan PC\Desktop\virtualenv\tutorial-env\huntr-exporter-main>python main.py
Traceback (most recent call last):
  File "C:\Users\RahMan PC\Desktop\virtualenv\tutorial-env\huntr-exporter-main\main.py", line 154, in <module>
    main()
  File "C:\Users\RahMan PC\Desktop\virtualenv\tutorial-env\huntr-exporter-main\main.py", line 142, in main
    driver = initialize_driver()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RahMan PC\Desktop\virtualenv\tutorial-env\huntr-exporter-main\main.py", line 132, in initialize_driver
    driver = webdriver.Chrome(os.getenv("WEBDRIVER_PATH"), options=set_chrome_options(os.getenv("ENVIRONMENT")))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got multiple values for argument 'options'

**Comment by chakrakan** [comment]
@diogo7santiago since you're on windows, are you updating your `.env` file's `WEBDRIVER_PATH` variable to point to the `.exe` file instead of the binary that's meant for unix systems? By default it uses the linux binary for chromedriver
